name: actions
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip install black
    - name: Check style with Black
      run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip install coverage matplotlib numpy pytest
    - name: Run tests
      run: coverage run -m pytest
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: .coverage
        retention-days: 1
        include-hidden-files: 'true'
  coverage_report:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install coverage
      - name: Generate Coverage Report
        run: |
          coverage report -m
          coverage xml
